version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/packages/cli"
    schedule:
      interval: "daily"
    allow:
      - dependency-name: "lucide-static"
    commit-message:
      prefix: "chore(deps):"
